/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Treasure_village_tastion_fortress;

import kaptainwutax.seedutils.mc.pos.BPos;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Map;
import java.util.Scanner;

class StructureSeedThread extends Thread {
    public static long START_SEED;
    public static long MAX_SEEDS;
    public int threadCount;
    public int offset;

    StructureSeedThread(int offset, int threadCount) {
        this.threadCount = threadCount;
        this.offset = offset;
    }

    public void run()
    {
        try {
            System.out.println(
                    "Thread " + Thread.currentThread().getId()
                            + " is running");

            StructureSeedFilter.filterStructureSeeds(this.threadCount, START_SEED, this.offset, MAX_SEEDS);
        }
        catch (Exception e) {
            System.out.println("Exception is caught");
        }
    }
}

public class Main {
    public static final String OPTIONS_PATHNAME = "options.txt";
    public static final String STRUCTURE_SEEDS_PATHNAME = "output-structureSeeds.txt";

    public static int THREAD_COUNT;

    public static void createThread(int t) throws InterruptedException {
        if (t < THREAD_COUNT - 1) {
            Runnable structureSeedThread = new StructureSeedThread(t, THREAD_COUNT);
            Thread thread = new Thread(structureSeedThread);
            thread.start();
            t++;
            createThread(t);
            thread.join();
        } else {
            Runnable structureSeedThread = new StructureSeedThread(t, THREAD_COUNT);
            Thread thread = new Thread(structureSeedThread);
            thread.start();
            thread.join();
        }
    }

    public static void main(String[] args) throws InterruptedException {
        try {
            File file = new File(OPTIONS_PATHNAME);
            Scanner reader = new Scanner(file);
            StructureSeedThread.START_SEED = Long.parseLong(reader.nextLine());
            StructureSeedThread.MAX_SEEDS = Integer.parseInt(reader.nextLine());
            THREAD_COUNT = Integer.parseInt(reader.nextLine());
            reader.close();
        } catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }

        StructureSeedFilter.filteredSeeds.clear();
        int t = 0;
        createThread(t);

        try {
            FileWriter writer = new FileWriter(STRUCTURE_SEEDS_PATHNAME);
            for (long filteredSeed : StructureSeedFilter.filteredSeeds) {
                writer.write(filteredSeed + "\n");
            }
            writer.close();
        } catch (IOException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
    }
}
